# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages:
          - commit-msg
        args: []
  - repo: https://github.com/pre-commit/pre-commit.git
    rev: v4.0.1
    hooks:
      - id: validate_manifest
  - repo: https://github.com/editorconfig-checker/editorconfig-checker
    rev: v3.2.0
    hooks:
      - id: editorconfig-checker
        stages:
          - pre-commit
  - repo: local
    hooks:
      - id: pass-tests
        name: Ensure the testsuite is passing
        entry: make test
        language: system
        pass_filenames: false
        stages:
          - pre-commit

